require_relative './tea/cli'
require_relative './tea/person'
require_relative './tea/store'
require_relative './tea/teas'
require_relative './tea/version'
#require 'pry'
#require 'nokogiri'
#require 'open_URI'
